### ISSUE TITLE
Suggestion: Moving Text related methods in it's own utility class

### ISSUE THREAD

**Issue by luigitus** [unlink2/memebotj#58]
While working on Memebot the usage of the method Meebot.formatText is one of the most important helper method to format text, replacing it with the data into {game}, {sender}, {points} and more.
A typical way how a command prepares a message before sending it:
```java 
getChannelHandler().sendMessage(Memebot.formatText("PB_NO_USER_AND_GAME", getChannelHandler(), sender, this, true, new String[]{}, ""), getChannelHandler().getChannel(), sender, isWhisper());
```
In my opinion it's time to move the text formatting into it's own utility class, my reasoning behind it is pretty simple:

1. The Memebot main class should only contain methods that are important to running and managing the entire bot processes 
2. Additional text formatting methods, if they could proof useful, can be found in the same utility class, making it easier to find and further improve text related work.
3. The formatText method could be simplified with the help of "shadowing" the method, eg. if the method doesn't have any parameters to add or if there is no alternative text or going as far as making the locale boolean true by default
```java
// before 
Memebot.formatText("PB_NO_USER_AND_GAME", getChannelHandler(), sender, this, true, new String[]{}, "");

//after
Text.format("PB_NO_USER_AND_GAME", getChannelHandler(), sender, this);
```
My idea how it can look like
https://gist.github.com/luigitus/fbc29ebba606b0297ef2f820421330a8
And making the method in Memebot referencing the utility class
```java
/**
 * @deprecated This method is replaced by
 * {@link TextFormatting#format(String, ChannelHandler, UserHandler, CommandHandler, boolean, String[], String)}
 */
    @Deprecated
    public static String formatText(String fo, ChannelHandler channelHandler, UserHandler sender,
                                  CommandHandler commandHandler, boolean local, String[] params,
                                  String alternativeText) {
        return TextFormatting.format(fo, channelHandler, sender, commandHandler, local, params, alternativeText);
    }
```

**Comment by unlink2** [comment]
This is implemented as of commit 8e4d550
