### ISSUE TITLE
Bot crashes when overflowing the cooldown integer

### ISSUE THREAD

**Issue by luigitus** [unlink2/memebotj#8]
Dear maintainer,

I found a really shocking error in your bot: The channel thread crashes when you do something like this:
```
!editcommand !reset cooldown 2147483647+1
```

Fix your stuff pls

Best regards
Your best bug reporter

**Comment by unlink2** [comment]
This issue has been fixed in the latest development build and will be merged to master shortly.

Thanks for your help.
